export const FETCH_CAMPAIGNS_DATA = 'FETCH_CAMPAIGNS_DATA'; 
export const FETCH_CAMPAIGNS_DATA_FAILURE = 'FETCH_CAMPAIGNS_DATA_FAILURE'; 
export const FETCH_CAMPAIGNS_DATA_NOT_FOUND = 'FETCH_CAMPAIGNS_DATA_NOT_FOUND'; 
export const CAMPAIGNS_NEW_DATA = 'CAMPAIGNS_NEW_DATA'; 